# =============================================================================
# design_mutagenesis_oligo_libraries.R — Design mutagenesis oligo libraries
#
# INPUT:  libraries_design/02_mutagenesis_libraires/output/exon_list_with_metadata.tsv
#         Generated by 00_add_genomic_metadata.R — run that script first.
#         One row per exon (608 exons total), columns include:
#           - ensembl_exon_id, exon_id, vastdb_event, gene_name
#           - exon_length         : length of the exon only (nt)
#           - wildtype_sequence   : full oligo = 70nt_5'intron + exon + 25nt_3'intron
#           - sat_mutagenesis_library_id : P1/P2/P3 (pilot) or MUT1–MUT6
#           - chr, strand, coord_start, coord_end, ensembl_gene_id
#           - ensembl_transcript_id, mane_select_nm, exon_number
#
# OUTPUT (per library, in output/per_library/):
#   - variant_mapping_MUT{n}.tsv  : barcode–variant mapping table (input to pipeline)
#   - oligos_MUT{n}.tsv            : Twist oligo order file
#   - summary_MUT{n}.tsv           : oligo count summary per exon
#
# COMBINED outputs (in output/):
#   - variant_mapping_all.tsv     : all libraries merged (input to pipeline step 01)
#   - summary_all.tsv              : total oligo counts per library
#
# NOTE: Reference/common variants are added in the NEXT script (add_refmut_from_pilot.R).
#       Run this script first, then add_refmut_from_pilot.R.
#
# CONSTANT sequences flanking every synthesised oligo (Gibson cloning homology arms):
#   5' arm: AAAAACCAATCACTCTTGATTACTA
#   3' arm: CAGATTGAAATAACTTGGGAAGTAG
# =============================================================================

suppressPackageStartupMessages({
  library(here)
  library(data.table)
  library(dplyr)
})

source(here("config.R"))   # loads FLANK_5SS, FLANK_3SS if set; otherwise defaults below

FLANK_5SS  <- 70    # nt of 5' intronic flanking sequence in the oligo
FLANK_3SS  <- 25    # nt of 3' intronic flanking sequence in the oligo
PRESEQ     <- "AAAAACCAATCACTCTTGATTACTA"   # 5' Gibson cloning arm
POSTSEQ    <- "CAGATTGAAATAACTTGGGAAGTAG"   # 3' Gibson cloning arm
DEL_SIZES  <- c(1, 3, 6, 21)               # deletion sizes to generate

# Which library IDs to process.
# NULL = process everything in the input file (P1/P2/P3 and MUT1–MUT6).
# Set to a character vector to restrict, e.g.: c("MUT1", "MUT2")
LIBS_TO_PROCESS <- NULL

# Directories
DIR_EXON_LIST <- here("libraries_design", "02_mutagenesis_libraries")
DIR_OUT       <- here("libraries_design", "02_mutagenesis_libraries", "output")
DIR_PER_LIB   <- file.path(DIR_OUT, "per_library")

dir.create(DIR_OUT,     showWarnings = FALSE, recursive = TRUE)
dir.create(DIR_PER_LIB, showWarnings = FALSE, recursive = TRUE)

# =============================================================================
# FUNCTION: generate all SNVs and 1/3/6/21 nt deletions for a given sequence
# Input : character string (full oligo: intron_up + exon + intron_down)
# Output: data.frame with columns nt_seq, identifier, start, end, length
# =============================================================================

design_oligos <- function(oligo_seq) {

  # ---- SNVs ------------------------------------------------------------------
  n   <- nchar(oligo_seq)
  nts <- c("A", "C", "G", "T")

  sub_rows <- vector("list", n)
  for (pos in seq_len(n)) {
    up  <- substr(oligo_seq, 1, pos - 1)
    dn  <- substr(oligo_seq, pos + 1, n)
    ref <- substr(oligo_seq, pos, pos)
    alts <- setdiff(nts, ref)
    sub_rows[[pos]] <- data.frame(
      nt_seq     = paste0(up, alts, dn),
      identifier = paste0(ref, pos, alts),
      start      = pos,
      end        = pos,
      length     = 1L,
      stringsAsFactors = FALSE
    )
  }
  snv_df <- do.call(rbind, sub_rows)

  # ---- Deletions -------------------------------------------------------------
  del_rows <- list()
  for (pos in seq_len(n)) {
    up_seq   <- substr(oligo_seq, 1, pos - 1)
    tail_seq <- substr(oligo_seq, pos, n)
    for (del_size in DEL_SIZES) {
      if (nchar(tail_seq) >= del_size) {
        del_rows[[length(del_rows) + 1]] <- data.frame(
          nt_seq     = paste0(up_seq, substr(tail_seq, 1 + del_size, nchar(tail_seq))),
          identifier = paste0("del", pos, "to", pos + del_size - 1),
          start      = pos,
          end        = pos + del_size - 1,
          length     = as.integer(del_size),
          stringsAsFactors = FALSE
        )
      }
    }
  }
  del_df <- do.call(rbind, del_rows)

  rbind(snv_df, del_df)
}

# =============================================================================
# LOAD EXON LIST
# =============================================================================

exon_list_file <- file.path(DIR_EXON_LIST, "exon_list_with_metadata.tsv")
if (!file.exists(exon_list_file)) {
  stop("Metadata file not found: ", exon_list_file,
       "\n  Run 00_add_genomic_metadata.R first.")
}

geneinfo <- fread(exon_list_file)
message(sprintf("Loaded %d exons from %s", nrow(geneinfo), basename(exon_list_file)))
message("Library breakdown: ")
print(table(geneinfo$sat_mutagenesis_library_id))

# Filter to requested libraries (NULL = all)
if (!is.null(LIBS_TO_PROCESS)) {
  geneinfo_mut <- geneinfo[sat_mutagenesis_library_id %in% LIBS_TO_PROCESS]
} else {
  geneinfo_mut <- geneinfo
}
message(sprintf("\nDesigning oligos for %d exons across libraries: %s",
                nrow(geneinfo_mut),
                paste(sort(unique(geneinfo_mut$sat_mutagenesis_library_id)), collapse = ", ")))

# =============================================================================
# MAIN LOOP: one exon at a time
# =============================================================================

variant_mapping_all <- data.frame()
summary_all          <- data.frame()

for (lib_id in sort(unique(geneinfo_mut$sat_mutagenesis_library_id))) {

  lib_exons     <- geneinfo_mut[sat_mutagenesis_library_id == lib_id]
  Twist_oligo_lib   <- data.frame()
  variant_lib      <- data.frame()
  summary_lib       <- data.frame()

  message(sprintf("\n[%s] Processing %d exons...", lib_id, nrow(lib_exons)))

  for (i in seq_len(nrow(lib_exons))) {

    exon_id         <- lib_exons$exon_id[i]
    ensembl_exon_id <- lib_exons$ensembl_exon_id[i]
    vastdb_event    <- lib_exons$vastdb_event[i]
    exon_len        <- as.integer(lib_exons$exon_length[i])
    wt_oligo     <- lib_exons$wildtype_sequence[i]   # flank_5ss + exon + 25nt_dn
    oligo_len    <- nchar(wt_oligo)

    # Derive actual 5' flank from real oligo length — handles exons where the
    # upstream intron was shortened (< 70 nt) to fit synthesis constraints
    actual_flank_5ss <- oligo_len - exon_len - FLANK_3SS
    if (actual_flank_5ss < 0) {
      stop(sprintf("Exon %s: oligo length (%d) shorter than exon + 3'flank (%d). Check wildtype_sequence.",
                   exon_id, oligo_len, exon_len + FLANK_3SS))
    }

    wt_exon_seq <- substr(wt_oligo, actual_flank_5ss + 1, actual_flank_5ss + exon_len)

    # Generate all variants
    edited <- design_oligos(wt_oligo)

    # Map oligo positions → exon-centric coordinates using actual flank length
    # Position 1..actual_flank_5ss          = -actual_flank_5ss..-1 (upstream intron)
    # Position actual_flank_5ss+1..+exon_len = 1..exon_len           (exon)
    # Position thereafter..end               = 1..FLANK_3SS           (downstream intron)
    exoncoord <- data.table(
      oligocoord = seq_len(oligo_len),
      exoncoord  = c(seq(-actual_flank_5ss, -1), seq_len(exon_len), seq_len(FLANK_3SS))
    )
    setkey(exoncoord, oligocoord)

    edited$start_corr <- exoncoord[.(edited$start)]$exoncoord
    edited$end_corr   <- exoncoord[.(edited$end)]$exoncoord

    # Derive the exonic sequence for each variant (what ends up in the exon after mutation)
    start_intron_dn <- actual_flank_5ss + exon_len   # last oligo position that is still exon

    edited$exonic_seq <- NA_character_

    for (j in seq_len(nrow(edited))) {
      s      <- edited$start[j]
      e      <- edited$end[j]
      is_del <- grepl("del", edited$identifier[j])

      if (s > actual_flank_5ss && e <= start_intron_dn && !is_del) {
        # SNV fully in exon
        edited$exonic_seq[j] <- substr(edited$nt_seq[j], actual_flank_5ss + 1, start_intron_dn)

      } else if (s > actual_flank_5ss && e <= start_intron_dn && is_del) {
        # Deletion fully in exon
        edited$exonic_seq[j] <- substr(edited$nt_seq[j], actual_flank_5ss + 1,
                                        start_intron_dn - edited$length[j])

      } else if (s <= actual_flank_5ss && e > actual_flank_5ss && e <= start_intron_dn) {
        # Deletion spanning 5' intron–exon boundary
        edited$exonic_seq[j] <- substr(edited$nt_seq[j],
                                        actual_flank_5ss + 1 + edited$start_corr[j],
                                        start_intron_dn - edited$length[j])

      } else if (s > actual_flank_5ss && s <= start_intron_dn && e > start_intron_dn) {
        # Deletion spanning exon–3' intron boundary
        edited$exonic_seq[j] <- substr(edited$nt_seq[j], actual_flank_5ss + 1,
                                        start_intron_dn - (edited$length[j] - edited$end_corr[j]))

      } else {
        # Mutation entirely in intron → exonic sequence unchanged
        edited$exonic_seq[j] <- wt_exon_seq
      }
    }

    # Add Gibson arms to get the full synthesised amplicon
    edited$amplicon         <- paste0(PRESEQ, edited$nt_seq, POSTSEQ)
    edited$exon             <- exon_id
    edited$ensembl_exon_id  <- ensembl_exon_id

    # ── Illumina mapping table (one row per variant, including duplicates) ──
    illumina_ex <- edited %>%
      select(ensembl_exon_id, exon, identifier, start, end, length,
             start_corr, end_corr, exonic_seq, nt_seq)

    wt_row <- data.frame(
      ensembl_exon_id = ensembl_exon_id, exon = exon_id, identifier = "wt",
      start = NA, end = NA, length = NA, start_corr = NA, end_corr = NA,
      exonic_seq = wt_exon_seq, nt_seq = wt_oligo,
      stringsAsFactors = FALSE
    )
    illumina_ex <- bind_rows(wt_row, illumina_ex)
    variant_lib <- rbind(variant_lib, illumina_ex)

    # ── Twist order (deduplicated on oligo sequence) ──
    twist_ex <- edited %>%
      group_by(ensembl_exon_id, exon, nt_seq, amplicon) %>%
      summarise(identifier = paste(identifier, collapse = ", "), .groups = "drop")

    wt_twist <- data.frame(
      ensembl_exon_id = ensembl_exon_id, exon = vastdb_event, identifier = "wt",
      nt_seq = wt_oligo, amplicon = paste0(PRESEQ, wt_oligo, POSTSEQ),
      stringsAsFactors = FALSE
    )
    twist_ex <- bind_rows(wt_twist, twist_ex)
    # unique_identifier = exon_id + all identifiers sharing this nt_seq (comma-separated)
    twist_ex$unique_identifier <- paste0(exon_id, "_", twist_ex$identifier)
    Twist_oligo_lib <- rbind(Twist_oligo_lib, twist_ex)

    # ── Summary ──
    summary_lib <- rbind(summary_lib, data.frame(
      library_id   = lib_id,
      exon_id      = exon_id,
      vastdb_event = vastdb_event,
      exon_length  = exon_len,
      n_oligos     = nrow(twist_ex),
      stringsAsFactors = FALSE
    ))
  }

  # ── Save per-library outputs ──
  fwrite(variant_lib,
         file.path(DIR_PER_LIB, sprintf("variant_mapping_%s.tsv", lib_id)),
         sep = "\t", quote = FALSE)

  fwrite(Twist_oligo_lib,
         file.path(DIR_PER_LIB, sprintf("oligos_%s.tsv", lib_id)),
         sep = "\t", quote = FALSE)

  fwrite(summary_lib,
         file.path(DIR_PER_LIB, sprintf("summary_%s.tsv", lib_id)),
         sep = "\t", quote = FALSE)

  message(sprintf("  [%s] %d oligos across %d exons → output/per_library/",
                  lib_id, sum(summary_lib$n_oligos), nrow(lib_exons)))

  variant_mapping_all <- rbind(variant_mapping_all, variant_lib)
  summary_all          <- rbind(summary_all, summary_lib)
}

# =============================================================================
# SAVE COMBINED OUTPUTS
# =============================================================================

fwrite(variant_mapping_all,
       file.path(DIR_OUT, "variant_mapping_all.tsv"),
       sep = "\t", quote = FALSE)

fwrite(summary_all,
       file.path(DIR_OUT, "summary_all.tsv"),
       sep = "\t", quote = FALSE)

message("\nTotal oligos across all MUT libraries: ",
        scales::comma(sum(summary_all$n_oligos)))
message("Combined illumina mapping → output/variant_mapping_all.tsv")
message("NEXT STEP: run add_refmut_from_pilot.R to add reference oligos to MUT2–MUT6")
