## 04.2_branch_point_manual.R
## Branch-point analysis — Part 2: positional mutational sensitivity around
## manually annotated and LaBranchoR-predicted branch points.
##
## Inputs:
##   results/analysis/04_branchpoint/04.1_processing_data/psi_df_bp_labranchor.txt
##     (generated by 04.1_branch_point_processing_data.R)
##
## Outputs:
##   figures/04_branchpoint/04.2_branch_point_manual/
##     bp_heatmap_mut_type.png
##     bp_wt_nt_by_region.png
##     bp_violin_by_region.png
##     sub_bp_boxplot.png
##     heatmap_manual.pdf
##     violin_bp_manual.png
##     violin_bp_manual_zoom.png
##   results/analysis/04_branchpoint/04.2_branch_point_manual/
##     count_sub_del1_PPT.tsv

library(data.table)
library(dplyr)
library(ggplot2)
library(tibble)
library(scales)
library(tidyr)
library(stringr)
library(rstatix)
library(ggpubr)
library(here)

source(here("analysis", "config.R"))

plot_dir    <- here("figures", "04_branchpoint", "04.2_branch_point_manual")
results_dir <- here("results", "analysis", "04_branchpoint", "04.2_branch_point_manual")
dir.create(plot_dir,    showWarnings = FALSE, recursive = TRUE)
dir.create(results_dir, showWarnings = FALSE, recursive = TRUE)

# Directory produced by 04.1
data_dir <- here("results", "analysis", "04_branchpoint", "04.1_processing_data")

palette <- c(
  pos5 = "#8B0000",   # most positive
  pos4 = "firebrick",
  pos3 = "#F88379",
  pos2 = "#F4C2C2",
  pos1 = "#FFD1DC",
  mid  = "gray70",   # -0.5 to 0.5
  neg1 = "#E0FFFF",
  neg2 = "#AFDBF5",
  neg3 = "#7AAED4",
  neg4 = "steelblue",  #"#4A90E2", "#2c7fb8",
  neg5 = "#00416A"  # most negative
)

# ── Load files ────────────────────────────────────────────────────────────────
psi_df_bp <- fread(file.path(data_dir, "psi_df_bp_labranchor.txt"), sep = "\t")

psi_df_bp <- psi_df_bp %>%
  filter(!is.na(psi) & !is.na(wt_psi) & start < 67) %>%
  select(exon_id,variant_id,psi,delta_psi,delta_logit,significant,wt,mut,mut_type,coord_rel,label) %>%
  mutate(
    delta_bin = case_when(
      significant != "yes"                      ~ "mid",
      delta_logit <  -3                         ~ "neg5",
      delta_logit >= -3   & delta_logit < -2    ~ "neg4",
      delta_logit >= -2   & delta_logit < -1    ~ "neg3",
      delta_logit >= -1   & delta_logit < -0.5  ~ "neg2",
      delta_logit >= -0.5   & delta_logit < 0   ~ "neg1",
      delta_logit > 0 & delta_logit <= 0.5      ~ "pos1",
      delta_logit > 0.5  & delta_logit <= 1     ~ "pos2",
      delta_logit >  1  & delta_logit <= 2      ~ "pos3",
      delta_logit >  2  & delta_logit <= 3      ~ "pos4",
      delta_logit >  3                          ~ "pos5",
      TRUE                                      ~ "mid"   # safety
    ),
    delta_bin = factor(delta_bin, levels = names(palette)),
    mut_type  = ifelse(mut_type == 'sub', 'Sub', mut_type),
    mut_type  = factor(mut_type, levels = c('Sub', '∆1nt', '∆3nt', '∆6nt')),
    mut       = factor(mut, levels = c("∆6nt", "∆3nt", "∆1nt", "A", "G", "C", "U")),
    delta_bin = factor(delta_bin, levels = c("mid", "pos5", "pos4", "pos3", "pos2", "pos1",
                                             "neg5", "neg4", "neg3", "neg2", "neg1"))
  )

table_pos <- psi_df_bp %>%
  group_by(coord_rel, label) %>%
  summarise(n_exon = n_distinct(exon_id), .groups = "drop")

pos_ok <- table_pos$coord_rel[table_pos$n_exon > 15]

# ── Plot 1: BP heatmap by mut_type (manual exons) ────────────────────────────
p_bp_heatmap_mut_type <- ggplot(
  psi_df_bp %>% filter(coord_rel %in% pos_ok & label == 'manual'),
  aes(x = coord_rel - 6, fill = delta_bin)
) +
  geom_bar(position = "fill", width = 1) +
  scale_y_continuous(
    breaks = c(0, 0.5, 1),
    labels = percent_format(accuracy = 1, suffix = ""),
    name   = "Percentage of variants"
  ) +
  scale_fill_manual(
    values = palette,
    breaks = names(palette),
    name = expression(Delta*LogitPSI)
  ) +
  labs(y = "Percentage of variants") +
  geom_vline(xintercept = c(-6.5, 1.5), linewidth = 0.3, linetype = 'dashed') +
  scale_x_continuous(breaks = c(-40, -20, -6, 0, 10, 30),
                     labels = c('-40', '-20', '-6', 'A', '+10', '+30')) +
  theme_minimal() +
  theme(
    plot.background  = element_rect(color = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks       = element_line(color = 'black', linewidth = 0.5),
    axis.line        = element_line(color = 'black', linewidth = 0.5),
    axis.text        = element_text(size = 10, color = 'black', family = 'Helvetica'),
    axis.text.x      = element_text(size = 10, color = 'black', family = 'Helvetica'),
    axis.title.x     = element_blank(),
    axis.title.y     = element_text(size = 10, color = 'black', family = 'Helvetica'),
    legend.position  = 'none',
    strip.text       = element_text(size = 10, color = 'black', family = 'Helvetica')
  ) +
  facet_grid(rows = vars(mut_type))

ggsave(file.path(plot_dir, "bp_heatmap_mut_type.png"),
       plot = p_bp_heatmap_mut_type, height = 8, width = 10)

psi_df_bp <- psi_df_bp %>%
  mutate(region_intron_up = case_when(
    coord_rel %in% 1:7 ~ 'BP',
    coord_rel < 1 ~ 'before BP',
    coord_rel > 7 ~ 'PPT'
  ),
  mut_v2 = case_when(
    mut_type %in% c('∆3nt', '∆6nt') ~ mut,
    mut_type == 'Sub'  ~ paste0(wt, '>', mut),
    mut_type == '∆1nt' ~ paste0('∆', wt)
  ),
  region_intron_up = factor(region_intron_up, levels = c('before BP', 'BP', 'PPT')))

# ── Plot 2: WT nucleotide bar by region × mut_type ────────────────────────────
p_bp_wt_nt <- ggplot(
  psi_df_bp %>% filter(mut_type %in% c('Sub', '∆1nt')),
  aes(x = wt, fill = delta_bin)
) +
  geom_bar(position = "fill") +
  scale_y_continuous(
    name   = "Percentage of variants",
    breaks = c(0, 0.5, 1),
    labels = c(0, 50, 100)
  ) +
  scale_fill_manual(
    values = palette,
    breaks = names(palette),
    name = expression(Delta*LogitPSI)
  ) +
  labs(x = "WT nt") +
  theme_minimal() +
  theme(
    plot.background  = element_rect(color = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks       = element_line(color = 'black', linewidth = 0.5),
    axis.line        = element_line(color = 'black', linewidth = 0.5),
    axis.text        = element_text(size = 10, color = 'black', family = 'Helvetica'),
    axis.title       = element_text(size = 10, color = 'black', family = 'Helvetica'),
    legend.text      = element_text(size = 10, color = 'black', family = 'Helvetica'),
    legend.title     = element_text(size = 10, color = 'black', family = 'Helvetica'),
    strip.text       = element_text(size = 10, color = 'black', family = 'Helvetica'),
    legend.position  = 'none'
  ) +
  facet_grid(rows = vars(region_intron_up), cols = vars(mut_type),
             scales = 'free_x', space = 'free_x')

ggsave(file.path(plot_dir, "bp_wt_nt_by_region.png"),
       plot = p_bp_wt_nt, height = 6, width = 5)

# ── Table: Sub + ∆1nt effect counts in PPT region ────────────────────────────
count_sub_del1 <- psi_df_bp %>%
  filter(mut_type %in% c('Sub', '∆1nt') & !is.na(delta_logit) & region_intron_up == 'PPT') %>%
  mutate(delta_bin = case_when(
    delta_bin == 'mid'            ~ 'mid',
    grepl('pos', delta_bin)       ~ 'pos',
    grepl('neg', delta_bin)       ~ 'neg',
  )) %>%
  group_by(mut_type, wt, delta_bin) %>%
  summarise(n_var = n(), .groups = "drop")

fwrite(count_sub_del1, file.path(results_dir, "count_sub_del1_PPT.tsv"), sep = "\t")

# ── Plot 3: Violin ∆LogitPSI by region × mut_type ────────────────────────────
p_bp_violin_region <- ggplot(psi_df_bp, aes(x = region_intron_up, y = delta_logit,
                                             fill = region_intron_up)) +
  geom_violin(linewidth = 0.2, alpha = 0.5) +
  geom_boxplot(linewidth = 0.2, width = 0.1, outlier.size = 0.1) +
  scale_fill_manual(values = c("grey60", "firebrick", "steelblue")) +
  labs(x = "Intron up", y = '∆LogitPSI') +
  theme_minimal() +
  theme(
    plot.background  = element_rect(color = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks       = element_line(color = 'black', linewidth = 0.5),
    axis.line        = element_line(color = 'black', linewidth = 0.5),
    axis.text        = element_text(size = 10, color = 'black', family = 'Helvetica'),
    axis.title.x     = element_blank(),
    axis.title.y     = element_text(size = 10, color = 'black', family = 'Helvetica'),
    legend.text      = element_text(size = 10, color = 'black', family = 'Helvetica'),
    legend.title     = element_text(size = 10, color = 'black', family = 'Helvetica'),
    strip.text.y     = element_text(size = 10, color = 'black', family = 'Helvetica'),
    strip.text.x     = element_blank(),
    legend.position  = 'none'
  ) +
  facet_grid(rows = vars(mut_type), cols = vars(region_intron_up),
             scales = 'free_x', space = 'free_x')

ggsave(file.path(plot_dir, "bp_violin_by_region.png"),
       plot = p_bp_violin_region, height = 8, width = 6)

nrow(psi_df_bp[psi_df_bp$region_intron_up == 'before BP' & abs(delta_logit) > 0.5 & psi_df_bp$significant == 'yes',]) /
  nrow(psi_df_bp[psi_df_bp$region_intron_up == 'before BP',])
nrow(psi_df_bp[psi_df_bp$region_intron_up == 'BP' & abs(delta_logit) > 0.5 & psi_df_bp$significant == 'yes',]) /
  nrow(psi_df_bp[psi_df_bp$region_intron_up == 'BP',])
nrow(psi_df_bp[psi_df_bp$region_intron_up == 'PPT' & abs(delta_logit) > 0.5 & psi_df_bp$significant == 'yes',]) /
  nrow(psi_df_bp[psi_df_bp$region_intron_up == 'PPT',])

sub_bp <- psi_df_bp %>%
  filter(mut_type == 'Sub' & coord_rel %in% 1:7 & label == 'manual') %>%
  mutate(wt = ifelse(wt == 'T', 'U', wt),
         mut_v2 = paste0(wt, '>', mut))

nt_pal_light <- c(
  A = "#A9E6C7",
  U = "#F7B3B3",
  G = "#6B6B6B",
  C = "#A9C6FF"
)

# ── Plot 4: Boxplot ∆LogitPSI per BP position, by mutant nt ──────────────────
p_sub_bp_boxplot <- ggplot(sub_bp, aes(x = as.factor(coord_rel), y = delta_logit, fill = mut)) +
  geom_boxplot(outlier.size = 0.1, width = 0.8, linewidth = 0.2) +
  labs(x = "Type") +
  geom_hline(yintercept = 0, linewidth = 0.3, linetype = 'dashed', color = 'grey60') +
  scale_x_discrete(labels = c('Y', 'N', 'Y', 'U', 'R', 'A', 'Y')) +
  scale_fill_manual(values = nt_pal_light) +
  theme_minimal() +
  theme(
    plot.background  = element_rect(color = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks       = element_line(color = 'black', linewidth = 0.3),
    axis.line        = element_line(color = 'black', linewidth = 0.3),
    axis.text        = element_text(size = 10, color = 'black', family = 'Helvetica'),
    axis.title.y     = element_text(size = 10, color = 'black', family = 'Helvetica'),
    axis.title.x     = element_blank(),
    legend.text      = element_text(size = 10, color = 'black', family = 'Helvetica'),
    legend.title     = element_text(size = 10, color = 'black', family = 'Helvetica'),
    strip.text       = element_text(size = 10, color = 'black', family = 'Helvetica')
  ) +
  labs(y = '∆LogitPSI', fill = 'Mutant') +
  facet_wrap(~wt)

ggsave(file.path(plot_dir, "sub_bp_boxplot.png"),
       plot = p_sub_bp_boxplot, height = 5, width = 6)

# ── Heatmap and violin: mutational signature at BP positions ──────────────────

delta_colours <- colorRampPalette(
  c("#2171B5", "#4292C6", "#A6CEE3", "white", "#FDAEAE", "#FB6A4A", "#EF3B2C")
)(200)

label_consensus <- data.frame(pos = 1:7,
                               consensus = c("Y", "N", "Y", "U", "R", "A", "Y"))

plot_heatmap <- function(df,
                         x         = coord_rel,
                         y         = exon_id,
                         fill      = median,
                         label_col = NULL,
                         pseudo_log = FALSE,
                         sigma     = 10,
                         limits    = c(-100, 100),
                         x_labels  = NULL,
                         legend    = FALSE,
                         facet_row = NULL,
                         facet_col = NULL) {
  fill_scale <- if (pseudo_log) {
    scale_fill_gradientn(
      colours = delta_colours,
      limits = c(-100, 100),
      breaks = c(-100, -50, -25, -5, 0, 5, 25, 50, 100),
      trans  = scales::pseudo_log_trans(sigma = 10),
      oob    = scales::squish,
      guide = guide_colourbar(
        barwidth  = unit(5, "cm"),
        barheight = unit(3, "mm")
      ),
      na.value = "grey60",
    )
  } else {
    scale_fill_gradientn(colours = delta_colours, limits = limits,
                         oob = squish, guide = "colourbar", na.value = "grey80")
  }
  p <- ggplot(df, aes(x = as.factor({{ x }}), y = {{ y }}, fill = {{ fill }})) +
    geom_tile() + fill_scale +
    theme_minimal() +
    theme(panel.grid = element_blank(), axis.ticks = element_blank(),
          axis.title = element_blank(), axis.text = element_blank(),
          legend.text  = element_text(size = 10, color = "black"),
          legend.title = element_text(size = 10, color = "black"),
          plot.background = element_rect(color = NA),
          strip.text.y = element_blank(),
          legend.position = if (legend) "bottom" else "none") +
    labs(fill = "Median ∆PSI Substitution")
  if (!is.null(label_col))
    p <- p + geom_text(aes(label = .data[[label_col]]), size = 5)
  if (!is.null(x_labels))
    p <- p + scale_x_discrete(breaks = x_labels$pos, labels = x_labels$consensus)
  if (!is.null(facet_row) || !is.null(facet_col))
    p <- p + facet_grid(rows = facet_row, cols = facet_col,
                        scales = "free", space = "free")
  p
}

plot_violin <- function(df, x = coord_rel, y = delta_psi,
                        x_labels = NULL, faceted = FALSE, facet_var = mut_type) {
  p <- ggplot(df, aes(x = as.factor({{ x }}), y = {{ y }})) +
    geom_violin(color = "black", linewidth = 0.2, width = 1,
                alpha = 0.5, fill = "#A6CEE3") +
    geom_boxplot(color = "black", linewidth = 0.2, width = 0.1,
                 outliers = FALSE, fill = "#A6CEE3") +
    stat_summary(aes(group = 1), fun = median, geom = "line",
                 linewidth = 0.4, color = "black") +
    theme_minimal() +
    theme(axis.line    = element_line(color = "black"),
          axis.ticks   = element_line(color = "black"),
          axis.text    = element_text(size = 10, color = "black", family = "Helvetica"),
          axis.title.x = element_blank(),
          axis.text.y  = element_text(size = 10, color = "black", family = "Helvetica"),
          panel.border = element_blank(), panel.grid = element_blank(),
          legend.position = "none") +
    ylab("∆PSI")
  if (!is.null(x_labels))
    p <- p + scale_x_discrete(breaks = x_labels$pos, labels = x_labels$consensus)
  if (faceted) p <- p + facet_grid(rows = vars({{ facet_var }}))
  p
}

cluster_exons <- function(df, k = 2) {
  mat <- df %>%
    filter(coord_rel %in% 1:7, mut_type == "sub", order_bp == 1) %>%
    group_by(exon_id, coord_rel) %>%
    summarise(median = median(delta_logit, na.rm = TRUE), .groups = "drop") %>%
    pivot_wider(names_from = coord_rel, values_from = median) %>%
    column_to_rownames("exon_id") %>%
    as.matrix()
  mat[is.na(mat)] <- 0
  hc <- hclust(dist(mat, method = "manhattan"), method = "ward.D2")
  data.frame(exon_id = hc$labels, order = hc$order,
             cluster = cutree(hc, k = k)) %>%
    arrange(cluster, order) %>%
    mutate(exon_id = factor(exon_id, levels = exon_id))
}

# Reload with all columns needed for clustering and heatmap (psi_df_bp
# above was filtered to start < 67 and had columns dropped)
psi_df_bp_full <- fread(file.path(data_dir, "psi_df_bp_labranchor.txt"), sep = "\t")
psi_df_bp_full$mut_type <- factor(psi_df_bp_full$mut_type,
                                   levels = c("sub", "∆1nt", "∆3nt", "∆6nt"))

order_row_manual <- psi_df_bp_full %>%
  filter(label == "manual") %>%
  cluster_exons(k = 1)

bp_median_manual <- psi_df_bp_full %>%
  filter(label == "manual", mut_type == "sub") %>%
  group_by(exon_id, start, coord_rel, wt, wt_psi, label, order_bp) %>%
  summarise(median = median(delta_psi, na.rm = TRUE), .groups = "drop") %>%
  mutate(exon_id = factor(exon_id, levels = levels(order_row_manual$exon_id))) %>%
  left_join(order_row_manual, by = "exon_id")

psi_df_bp_manual <- psi_df_bp_full %>%
  filter(label == "manual") %>%
  mutate(exon_id = factor(exon_id, levels = levels(order_row_manual$exon_id)))

p_heatmap_manual <- plot_heatmap(bp_median_manual, pseudo_log = TRUE,
                                  x_labels = label_consensus, legend = TRUE)

p_violin_manual <- plot_violin(
  psi_df_bp_manual %>% filter(coord_rel < 60, mut_type == "sub"),
  x_labels = label_consensus)

p_violin_manual_zoom <- plot_violin(
  psi_df_bp_manual %>% filter(coord_rel %in% -3:20, mut_type == "sub"),
  y = delta_psi, x_labels = label_consensus)

ggsave(file.path(plot_dir, "heatmap_manual.pdf"),
       p_heatmap_manual, height = 60, width = 40, limitsize = FALSE)
ggsave(file.path(plot_dir, "violin_bp_manual.png"),
       p_violin_manual, height = 4, width = 30, limitsize = FALSE)
ggsave(file.path(plot_dir, "violin_bp_manual_zoom.png"),
       p_violin_manual_zoom, height = 10, width = 10, limitsize = FALSE)

