## 04.3_branch_point_mercer_taggart_labranchor.R
## Branch-point analysis — Part 3: clustering, plots, reference dataset
## comparisons, and supplementary table.
##
## Inputs:
##   results/analysis/04_branchpoint/04.1_processing_data/
##     psi_df_bp_labranchor.txt, labranchor.txt, mercer.txt, taggart.txt,
##     manual_predicted_labranchor.txt, lab_long.txt, lab_top.txt,
##     top1_pos_key.txt, top1_lab.txt
##     (all generated by 04.1_branch_point_processing_data.R)
##   MASTER_TABLE
##   libraries_design/02_mutagenesis_libraries/output/genomic_coord_mut.tsv
##
## Outputs:
##   figures/04_branchpoint/04.3_branch_point_mercer_taggart_labranchor/
##     heatmap_predicted.png
##     violin_bp_predicted_group1_zoom.png
##     violin_bp_predicted_group2_zoom.png
##     violin_prob_rank1_by_group.png
##     violin_prob_rank2_by_group.png
##     violin_prob_diff_by_group.png
##     violin_pos_diff_by_group.png
##     violin_n_additional_bp_by_group.png
##     violin_nearest_additional_bp_by_group.png
##     bp_position_density.png
##   results/analysis/04_branchpoint/04.3_branch_point_mercer_taggart_labranchor/
##     bp_cluster_groups.tsv
##     additional_bp_summary.tsv
##     prob_stats_by_group_rank.tsv
##     lab_groups_prob_by_rank.tsv
##     prob_diff_by_group.tsv
##     wtest_prob_rank1.tsv
##     wtest_prob_rank2.tsv
##     wtest_prob_diff.tsv
##     pos_diff_by_group.tsv
##     wtest_pos_diff.tsv
##     add_bp_stats_by_group.tsv
##     wtest_n_additional_bp.tsv
##     wtest_nearest_additional_bp.tsv
##     match_results.tsv
##     match_summary_by_label.tsv
##     mercer_vs_taggart_bp_comparison.tsv
##     mercer_vs_labranchor_bp_comparison.tsv
##     taggart_vs_labranchor_bp_comparison.tsv
##     supplementary_table_top_BP.tsv

library(data.table)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)
library(stringr)
library(ggplot2)
library(scales)
library(rstatix)
library(ggpubr)
library(here)

source(here("analysis", "config.R"))

# ── Paths ─────────────────────────────────────────────────────────────────────
data_dir    <- here("results", "analysis", "04_branchpoint", "04.1_processing_data")
plot_dir    <- here("figures", "04_branchpoint", "04.3_branch_point_mercer_taggart_labranchor")
results_dir <- here("results", "analysis", "04_branchpoint", "04.3_branch_point_mercer_taggart_labranchor")
dir.create(plot_dir,    showWarnings = FALSE, recursive = TRUE)
dir.create(results_dir, showWarnings = FALSE, recursive = TRUE)

# ── Load files ────────────────────────────────────────────────────────────────
psi_df_bp    <- fread(file.path(data_dir, "psi_df_bp_labranchor.txt"), sep = "\t")
labranchor   <- fread(file.path(data_dir, "labranchor.txt"),           sep = "\t")
mercer       <- fread(file.path(data_dir, "mercer.txt"),               sep = "\t")
taggart      <- fread(file.path(data_dir, "taggart.txt"),              sep = "\t")
bp_7mers     <- fread(file.path(data_dir, "manual_predicted_labranchor.txt"), sep = "\t")
psi_df       <- fread(MASTER_TABLE, sep = "\t")
lab_long     <- fread(file.path(data_dir, "lab_long.txt"),     sep = "\t")
lab_top      <- fread(file.path(data_dir, "lab_top.txt"),      sep = "\t")
top1_pos_key <- fread(file.path(data_dir, "top1_pos_key.txt"), sep = "\t")
top1_lab     <- fread(file.path(data_dir, "top1_lab.txt"),     sep = "\t")

# ── 1.6 Cluster exons by BP mutational signature ──────────────────────────────

cluster_exons <- function(df, k = 2) {
  mat <- df %>%
    filter(coord_rel %in% 1:7, mut_type == "sub", order_bp == 1) %>%
    group_by(exon_id, coord_rel) %>%
    summarise(median = median(delta_psi, na.rm = TRUE), .groups = "drop") %>%
    pivot_wider(names_from = coord_rel, values_from = median) %>%
    column_to_rownames("exon_id") %>%
    as.matrix()
  mat[is.na(mat)] <- 0
  hc <- hclust(dist(mat, method = "manhattan"), method = "ward.D2")
  data.frame(exon_id = hc$labels, order = hc$order,
             cluster = cutree(hc, k = k)) %>%
    arrange(cluster, order) %>%
    mutate(exon_id = factor(exon_id, levels = exon_id))
}

psi_df_bp$mut_type <- factor(psi_df_bp$mut_type,
                             levels = c("sub", "∆1nt", "∆3nt", "∆6nt"))

order_row_manual <- psi_df_bp %>%
  filter(label == "manual") %>%
  cluster_exons(k = 1)

order_row_predicted <- psi_df_bp %>%
  filter(label == "predicted", wt_psi >= 5, wt_psi <= 95, order_bp == 1) %>%
  cluster_exons(k = 2)

groups <- bind_rows(
  order_row_manual    %>% transmute(exon_id = as.character(exon_id),
                                    group   = "Yes\nManual"),
  order_row_predicted %>% transmute(exon_id = as.character(exon_id),
                                    group   = ifelse(cluster == 1,
                                                     "Yes\nPredicted",
                                                     "No\nPredicted"))
) %>%
  mutate(group = factor(group,
                        levels = c("Yes\nManual", "Yes\nPredicted", "No\nPredicted")))

# Export cluster labels (used by downstream comparison analyses)
groups %>%
  mutate(cluster_label = case_when(
    group == "Yes\nManual"    ~ "Manual",
    group == "Yes\nPredicted" ~ "Predicted Cluster 1",
    group == "No\nPredicted"  ~ "Predicted Cluster 2"
  )) %>%
  select(exon_id, cluster_label) %>%
  fwrite(file.path(results_dir, "bp_cluster_groups.tsv"), sep = "\t")

lab_groups <- lab_top %>% inner_join(groups, by = "exon_id")

cat("Clustering done:",
    sum(groups$group == "Yes\nManual"),    "manual |",
    sum(groups$group == "Yes\nPredicted"), "predicted cluster 1 |",
    sum(groups$group == "No\nPredicted"),  "predicted cluster 2\n")

# ══════════════════════════════════════════════════════════════════════════════
# 2. PLOTS
# ══════════════════════════════════════════════════════════════════════════════

# ── 2.0 Shared aesthetics ─────────────────────────────────────────────────────

group_cols <- c("Yes\nManual"    = "firebrick",
                "Yes\nPredicted" = "steelblue",
                "No\nPredicted"  = "grey60")

delta_colours <- colorRampPalette(
  c("#2171B5", "#4292C6", "#A6CEE3", "white", "#FDAEAE", "#FB6A4A", "#EF3B2C")
)(200)

label_consensus <- data.frame(pos = 1:7,
                              consensus = c("Y", "N", "Y", "U", "R", "A", "Y"))

base_theme <- theme_minimal() +
  theme(
    plot.background  = element_rect(color = NA),
    panel.grid       = element_blank(),
    axis.ticks       = element_line(color = "black", linewidth = 0.5),
    axis.line        = element_line(color = "black", linewidth = 0.5),
    axis.text        = element_text(size = 10, color = "black", family = "Helvetica"),
    axis.title       = element_text(size = 10, color = "black", family = "Helvetica"),
    legend.text      = element_text(size = 10, color = "black", family = "Helvetica"),
    legend.title     = element_text(size = 10, color = "black", family = "Helvetica")
  )

plot_heatmap <- function(df,
                         x         = coord_rel,
                         y         = exon_id,
                         fill      = median,
                         label_col = NULL,
                         pseudo_log = FALSE,
                         sigma     = 10,
                         limits    = c(-100, 100),
                         x_labels  = NULL,
                         legend    = FALSE,
                         facet_row = NULL,
                         facet_col = NULL) {
  fill_scale <- if (pseudo_log) {
    scale_fill_gradientn(colours = delta_colours, limits = limits,
                         breaks = c(-100, -50, -25, -5, 0, 5, 25, 50, 100),
                         trans = pseudo_log_trans(sigma = sigma), oob = squish,
                         guide = "colourbar", na.value = "grey60")
  } else {
    scale_fill_gradientn(colours = delta_colours, limits = limits,
                         oob = squish, guide = "colourbar", na.value = "grey80")
  }
  p <- ggplot(df, aes(x = as.factor({{ x }}), y = {{ y }}, fill = {{ fill }})) +
    geom_tile() + fill_scale +
    theme_minimal() +
    theme(panel.grid = element_blank(), axis.ticks = element_blank(),
          axis.title = element_blank(), axis.text = element_blank(),
          legend.text  = element_text(size = 14, color = "black"),
          legend.title = element_text(size = 14, color = "black"),
          plot.background = element_rect(color = NA),
          strip.text.y = element_blank(),
          legend.position = if (legend) "bottom" else "none") +
    labs(fill = "∆PSI")
  if (!is.null(label_col))
    p <- p + geom_text(aes(label = .data[[label_col]]), size = 5)
  if (!is.null(x_labels))
    p <- p + scale_x_discrete(breaks = x_labels$pos, labels = x_labels$consensus)
  if (!is.null(facet_row) || !is.null(facet_col))
    p <- p + facet_grid(rows = facet_row, cols = facet_col,
                        scales = "free", space = "free")
  p
}

plot_violin <- function(df, x = coord_rel, y = delta_psi,
                        x_labels = NULL, faceted = FALSE, facet_var = mut_type) {
  p <- ggplot(df, aes(x = as.factor({{ x }}), y = {{ y }})) +
    geom_violin(color = "black", linewidth = 0.2, width = 1,
                alpha = 0.5, fill = "#A6CEE3") +
    geom_boxplot(color = "black", linewidth = 0.2, width = 0.1,
                 outliers = FALSE, fill = "#A6CEE3") +
    stat_summary(aes(group = 1), fun = median, geom = "line",
                 linewidth = 0.4, color = "black") +
    theme_minimal() +
    theme(axis.line    = element_line(color = "black"),
          axis.ticks   = element_line(color = "black"),
          axis.text    = element_text(size = 10, color = "black", family = "Helvetica"),
          axis.title.x = element_blank(),
          axis.text.y  = element_text(size = 10, color = "black", family = "Helvetica"),
          panel.border = element_blank(), panel.grid = element_blank(),
          legend.position = "none") +
    ylab("∆PSI")
  if (!is.null(x_labels))
    p <- p + scale_x_discrete(breaks = x_labels$pos, labels = x_labels$consensus)
  if (faceted) p <- p + facet_grid(rows = vars({{ facet_var }}))
  p
}

plot_group_violin <- function(data, y_var, y_lab, title_str, step_increase = 5,
                             out_path = NULL) {
  wtest <- data %>%
    wilcox_test(as.formula(paste(y_var, "~ group")),
                paired = FALSE, p.adjust.method = "BH") %>%
    add_significance() %>%
    add_xy_position(x = "group", step.increase = step_increase) %>%
    mutate(y.position = case_when(
      group1 == "Yes\nManual"    & group2 == "Yes\nPredicted" ~ min(y.position),
      group1 == "Yes\nPredicted" & group2 == "No\nPredicted"  ~ min(y.position),
      group1 == "Yes\nManual"    & group2 == "No\nPredicted"  ~ max(y.position),
      TRUE ~ y.position
    ),
    p.adj.signif = ifelse(p > 0.01, 'ns', p.adj.signif))
  cat("\n---", title_str, "---\n")
  wtest_out <- as.data.frame(wtest[, c("group1", "group2", "n1", "n2",
                                       "p", "p.adj", "p.adj.signif")])
  print(wtest_out)
  if (!is.null(out_path)) fwrite(wtest_out, out_path, sep = "\t")
  ggplot(data, aes(x = group, y = .data[[y_var]], fill = group)) +
    geom_violin(linewidth = 0.2, alpha = 0.6, width = 0.8, colour = "black") +
    geom_boxplot(linewidth = 0.2, width = 0.12, outliers = FALSE,
                 colour = "black", aes(fill = group), alpha = 0.8) +
    stat_pvalue_manual(wtest, label = "p.adj.signif", tip.length = 0.01,
                       size = 3.2, colour = "black", family = "Helvetica") +
    scale_fill_manual(values = group_cols) +
    labs(title = title_str, y = y_lab, x = NULL) +
    base_theme + theme(legend.position = "none") +
    coord_cartesian(clip = "off")
}

# ── 2.1 Heatmap and violin: predicted ─────────────────────────────────────────

bp_median_predicted <- psi_df_bp %>%
  filter(label == "predicted", wt_psi >= 5, wt_psi <= 95, order_bp == 1,
         mut_type == "sub") %>%
  group_by(exon_id, start, coord_rel, wt, wt_psi, label, order_bp) %>%
  summarise(median = median(delta_psi, na.rm = TRUE), .groups = "drop") %>%
  mutate(exon_id = factor(exon_id, levels = levels(order_row_predicted$exon_id))) %>%
  left_join(order_row_predicted, by = "exon_id")

p_heatmap_predicted <- plot_heatmap(bp_median_predicted,
                                    pseudo_log = TRUE, x_labels = label_consensus)

ggsave(file.path(plot_dir, "heatmap_predicted.png"),
       p_heatmap_predicted, height = 100, width = 40, limitsize = FALSE)

psi_df_bp_predicted <- psi_df_bp %>%
  filter(label == "predicted", wt_psi >= 5, wt_psi <= 95, order_bp == 1) %>%
  mutate(exon_id = factor(exon_id, levels = levels(order_row_predicted$exon_id)))

group1_exon <- order_row_predicted$exon_id[order_row_predicted$cluster == 1]
p_violin_predicted_group1 <- plot_violin(
  psi_df_bp_predicted %>% filter(coord_rel %in% -3:20, mut_type == "sub" & exon_id %in% group1_exon),
  x_labels = label_consensus)

group2_exon <- order_row_predicted$exon_id[order_row_predicted$cluster == 2]
p_violin_predicted_group2 <- plot_violin(
  psi_df_bp_predicted %>% filter(coord_rel %in% -3:20, mut_type == "sub" & exon_id %in% group2_exon),
  x_labels = label_consensus)

ggsave(file.path(plot_dir, "violin_bp_predicted_group1_zoom.png"), p_violin_predicted_group1, height = 10, width = 30, limitsize = FALSE)
ggsave(file.path(plot_dir, "violin_bp_predicted_group2_zoom.png"), p_violin_predicted_group2, height = 10, width = 30, limitsize = FALSE)


# ── 2.3 LaBranchoR probability by group ───────────────────────────────────────

prob_ranks <- lab_groups %>%
  filter(rank_bp %in% 1:2) %>%
  mutate(rank_label = paste0("Rank ", rank_bp))

prob_stats_by_group_rank <- prob_ranks %>%
  group_by(group, rank_label) %>%
  summarise(n = n(), median = round(median(prob), 3), mean = round(mean(prob), 3),
            .groups = "drop")
cat("\n=== BP probability by rank and group ===\n")
print(prob_stats_by_group_rank)
fwrite(prob_stats_by_group_rank, file.path(results_dir, "prob_stats_by_group_rank.tsv"), sep = "\t")

p_prob1 <- plot_group_violin(prob_ranks %>% filter(rank_bp == 1),
                              "prob", "Probability", "Top-1 BP probability", step_increase = 3,
                              out_path = file.path(results_dir, "wtest_prob_rank1.tsv"))
p_prob2 <- plot_group_violin(prob_ranks %>% filter(rank_bp == 2),
                              "prob", "Probability (rank 2)", "Top-2 BP probability", step_increase = 0.2,
                              out_path = file.path(results_dir, "wtest_prob_rank2.tsv"))

prob_diff <- lab_groups %>%
  filter(rank_bp %in% 1:2) %>%
  select(exon_id, group, rank_bp, prob) %>%
  pivot_wider(names_from = rank_bp, values_from = prob, names_prefix = "prob_rank") %>%
  filter(!is.na(prob_rank2)) %>%
  mutate(prob_diff = prob_rank1 - prob_rank2)

lab_groups_prob_by_rank <- lab_groups %>%
  group_by(group, rank_bp) %>%
  summarise(n = n(), median_prob = median(prob), .groups = "drop")
fwrite(lab_groups_prob_by_rank, file.path(results_dir, "lab_groups_prob_by_rank.tsv"), sep = "\t")

prob_diff_by_group <- prob_diff %>%
  group_by(group) %>%
  summarise(n = n(), median_prob_diff = median(prob_diff), .groups = "drop")
fwrite(prob_diff_by_group, file.path(results_dir, "prob_diff_by_group.tsv"), sep = "\t")

p_prob_diff <- plot_group_violin(prob_diff, "prob_diff",
                                 "∆Probability", "Top-1 − Top-2 BP", step_increase = 0.8,
                                 out_path = file.path(results_dir, "wtest_prob_diff.tsv"))

for (nm in c("prob_rank1", "prob_rank2", "prob_diff")) {
  p <- list(prob_rank1 = p_prob1, prob_rank2 = p_prob2,
            prob_diff = p_prob_diff)[[nm]]
  ggsave(file.path(plot_dir, paste0("violin_", nm, "_by_group.png")), p, height = 5, width = 5)
}

# ── 2.3b Distance between top-1 and top-2 BP positions ───────────────────────

pos_diff <- lab_groups %>%
  filter(rank_bp %in% 1:2) %>%
  select(exon_id, group, rank_bp, intron_pos) %>%
  pivot_wider(names_from = rank_bp, values_from = intron_pos,
              names_prefix = "pos_rank") %>%
  filter(!is.na(pos_rank2)) %>%
  mutate(pos_diff = abs(pos_rank1 - pos_rank2))

pos_diff_by_group <- pos_diff %>%
  group_by(group) %>%
  summarise(n = n(), median = median(pos_diff), mean = round(mean(pos_diff), 1),
            .groups = "drop")
cat("\n=== Top-1 vs Top-2 BP distance by group ===\n")
print(pos_diff_by_group)
fwrite(pos_diff_by_group, file.path(results_dir, "pos_diff_by_group.tsv"), sep = "\t")

p_pos_diff <- plot_group_violin(pos_diff, "pos_diff",
                                "Distance (nt)", "Top-1 vs Top-2 BP\ndistance",
                                step_increase = 0.2,
                                out_path = file.path(results_dir, "wtest_pos_diff.tsv"))

ggsave(file.path(plot_dir, "violin_pos_diff_by_group.png"), p_pos_diff, height = 5, width = 5)


# ── 2.4 Additional BPs: count, consensus match, distance from top-1 ──────────

# 7-mer sequences keyed by exon (A = pos 6 of YNYURAY, 7-mer = intron_pos-5 : intron_pos+1)
nt_seqs <- psi_df %>%
  filter(grepl('wt', variant_id)) %>%
  select(exon_id, nt_seq) %>%
  distinct() %>%
  inner_join(bp_7mers, by = 'exon_id')

# Sequence-based scan for additional BP motifs
# YNYURAY: Y(C/T) N(any) Y(C/T) U(T) R(A/G) A(A) Y(C/T)
# Filter: pos4=T and pos6=A required; max 2 mismatches among variable positions 1,3,5,7

# Total 7-position consensus score (max 7; pos 2=N always = 1)
score_7mer <- function(s) {
  if (is.na(s) || nchar(s) < 7) return(NA_integer_)
  n <- toupper(strsplit(s, "")[[1]])
  as.integer(sum(c(n[1] %in% c("C","T"), TRUE,
                   n[3] %in% c("C","T"), n[4] == "T",
                   n[5] %in% c("A","G"), n[6] == "A",
                   n[7] %in% c("C","T"))))
}

# Invariant positions must match exactly: pos4=T, pos6=A
has_invariants <- function(s) {
  if (is.na(s) || nchar(s) < 7) return(FALSE)
  n <- toupper(strsplit(s, "")[[1]])
  n[4] == "T" & n[6] == "A"
}

# Matches among the 4 variable positions: 1(Y), 3(Y), 5(R), 7(Y) — max 4
variable_score <- function(s) {
  if (is.na(s) || nchar(s) < 7) return(NA_integer_)
  n <- toupper(strsplit(s, "")[[1]])
  as.integer(n[1] %in% c("C","T") + n[3] %in% c("C","T") +
             n[5] %in% c("A","G") + n[7] %in% c("C","T"))
}

top1_coord <- nt_seqs %>%
  filter(order == 1L) %>%
  mutate(nt_seq = substr(nt_seq, 1, 66)) %>%
  select(exon_id, nt_seq, top1_start = bp_start)

add_bp <- top1_coord %>%
  inner_join(groups, by = "exon_id") %>%
  mutate(
    candidates = map2(nt_seq, top1_start, function(seq, top1) {
      starts <- seq_len(nchar(seq) - 6L)
      starts <- starts[is.na(top1) | starts != top1]
      data.frame(kmer_start = starts,
                 kmer = vapply(starts, function(s) substr(seq, s, s + 6L), character(1)))
    })
  ) %>%
  select(-nt_seq) %>%
  unnest(candidates) %>%
  mutate(
    n_consensus  = vapply(kmer, score_7mer,    integer(1)),
    n_variable   = vapply(kmer, variable_score, integer(1)),
    dist_to_top1 = abs(kmer_start - top1_start)
  ) %>%
  filter(vapply(kmer, has_invariants, logical(1)),  # pos4=T and pos6=A required
         n_variable >= 2)                            # max 2 mismatches among pos 1,3,5,7


# ── Summary table: 1 row per exon ─────────────────────────────────────────────

# Top-1 BP info (seq and start) from bp_7mers
top1_info <- bp_7mers %>%
  filter(order == 1L) %>%
  select(exon_id, start_top1 = bp_start, top1_bp_seq = bp_seq)

# Nearest additional BP per exon (closest to top-1 by position)
nearest_add <- add_bp %>%
  group_by(exon_id) %>%
  slice_min(dist_to_top1, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  select(exon_id,
         nearest_2nd_bp_start = kmer_start,
         nearest_2nd_bp_seq   = kmer,
         distance              = dist_to_top1)

# Count of additional BPs per exon
n_add_tbl <- add_bp %>%
  group_by(exon_id) %>%
  summarise(n_additional_bp = n(), .groups = "drop")

# One row per exon; exons with 0 additional BPs get n_additional_bp=0 and NA for nearest
add_bp_summary <- groups %>%
  left_join(top1_info,   by = "exon_id") %>%
  left_join(n_add_tbl,   by = "exon_id") %>%
  left_join(nearest_add, by = "exon_id") %>%
  select(exon_id, group, top1_bp_seq, start_top1,
         n_additional_bp, nearest_2nd_bp_start, nearest_2nd_bp_seq, distance) %>%
  mutate(n_additional_bp = replace_na(n_additional_bp, 0L),
         distance = replace_na(distance, 0L))

add_bp_stats_by_group <- add_bp_summary %>%
  group_by(group) %>%
  summarise(n = n(),
            median_n_add = median(n_additional_bp),
            pct_with_add = round(100 * mean(n_additional_bp > 0), 1),
            median_nt_nearest = median(distance),
            .groups = "drop")
cat("\n=== Additional BP summary (pos4=T, pos6=A, ≥2 variable matches) ===\n")
print(add_bp_stats_by_group)
fwrite(add_bp_stats_by_group, file.path(results_dir, "add_bp_stats_by_group.tsv"), sep = "\t")

fwrite(add_bp_summary, file.path(results_dir, "additional_bp_summary.tsv"), sep = "\t")

# -- Plot 1: number of additional BPs per exon (0 included) --
p_nadd <- plot_group_violin(add_bp_summary, "n_additional_bp",
                            "Number of additional BPs",
                            "Additional BPs",
                            step_increase = 0.1,
                            out_path = file.path(results_dir, "wtest_n_additional_bp.tsv"))

ggsave(file.path(plot_dir, "violin_n_additional_bp_by_group.png"), p_nadd, height = 5, width = 6)

# -- Plot 2: nearest distance from top-1 to nearest additional BP --
# exons with n_additional_bp == 0 are excluded (distance = NA)
p_nearest <- plot_group_violin(
  add_bp_summary %>% filter(!is.na(distance)),
  "distance",
  "Distance to nearest\nadditional BP (nt)",
  "Nearest additional\nBP to top-1",
  step_increase = 0.5,
  out_path = file.path(results_dir, "wtest_nearest_additional_bp.tsv"))

ggsave(file.path(plot_dir, "violin_nearest_additional_bp_by_group.png"), p_nearest, height = 5, width = 6)

# ── 2.5 Reference dataset vs predicted: match rates ───────────────────────────

TOLERANCES <- 0:4

# Add cluster label to bp_7mers for use as 'pred'
pred <- bp_7mers %>%
  left_join(groups %>%
              mutate(cluster_label = case_when(
                group == "Yes\nManual"    ~ "Manual",
                group == "Yes\nPredicted" ~ "Predicted Cluster 1",
                group == "No\nPredicted"  ~ "Predicted Cluster 2"
              )) %>%
              select(exon_id, cluster_label),
            by = "exon_id") %>%
  mutate(label_group = case_when(
    label == "manual"                         ~ "Yes\nManual",
    cluster_label == "Predicted Cluster 1"    ~ "Yes\nPredicted",
    cluster_label == "Predicted Cluster 2"    ~ "No\nPredicted",
    TRUE                                      ~ "Predicted (top-1)"
  )) %>%
  filter(label_group != "Predicted (top-1)")

build_merged <- function(ref) {
  inner_join(ref, pred, by = "exon_id", suffix = c("_ref", "_pred"),
             relationship = "many-to-many") %>%
    mutate(pred_bp_pos = bp_end_pred - 1L,
           dist        = abs(intron_up_coord - pred_bp_pos)) %>%
    {
      out <- .
      for (tol in TOLERANCES)
        out[[paste0("match_tol", tol)]] <- out$dist <= tol
      out
    }
}

merged_mercer     <- build_merged(mercer)
merged_taggart    <- build_merged(taggart)
merged_labranchor <- build_merged(labranchor)

exon_match_rate <- function(data, lbl, max_order, tol_col) {
  data %>%
    filter(label == lbl, order <= max_order) %>%
    group_by(exon_id) %>%
    summarise(any_match = any(.data[[tol_col]]), .groups = "drop") %>%
    summarise(matched = sum(any_match), total = n(), rate = mean(any_match))
}

summary_table <- function(merged_data, dataset_name) {
  map_dfr(TOLERANCES, function(tol) {
    tol_col <- paste0("match_tol", tol)
    bind_rows(
      exon_match_rate(merged_data, "manual", 1L, tol_col) %>%
        mutate(label = "manual", top_n = 1L),
      map_dfr(1:3, function(k) {
        exon_match_rate(merged_data, "predicted", k, tol_col) %>%
          mutate(label = "predicted", top_n = k)
      })
    ) %>% mutate(tolerance = tol)
  }) %>%
    mutate(dataset = dataset_name) %>%
    select(dataset, label, top_n, tolerance, matched, total, rate)
}

cat("\n=== Exon-level match rate ===\n")
match_results <- bind_rows(
  summary_table(merged_mercer,     "Mercer"),
  summary_table(merged_taggart,    "Taggart"),
  summary_table(merged_labranchor, "LaBranchoR")
)
print(match_results, n = Inf)
fwrite(match_results, file.path(results_dir, "match_results.tsv"), sep = "\t")

# ── 2.6 BP position distribution relative to 3'SS ────────────────────────────

pal_source <- c("Manual"    = "firebrick",
                "Predicted" = "grey60",
                "Mercer"    = "#AFDBF5",
                "Taggart"   = "#FFD1DC")

bp_pos_data <- bind_rows(
  mercer  %>% distinct(exon_id, intron_up_coord) %>% transmute(source = "Mercer",    pos = intron_up_coord),
  taggart %>% distinct(exon_id, intron_up_coord) %>% transmute(source = "Taggart",   pos = intron_up_coord),
  pred    %>% filter(label == "manual",    order == 1L) %>% transmute(source = "Manual",    pos = bp_end - 1L),
  pred    %>% filter(label == "predicted", order == 1L) %>% transmute(source = "Predicted", pos = bp_end - 1L)
) %>% mutate(source = factor(source, levels = c("Mercer", "Taggart", "Predicted", "Manual")))

median_df <- bp_pos_data %>%
  group_by(source) %>%
  summarise(median_pos = median(pos), .groups = "drop") %>%
  mutate(display_median = as.integer(median_pos - 71L),
         vjust_pos      = seq(1.5, by = 2.0, length.out = n()))

p_bp_pos <- ggplot(bp_pos_data, aes(x = pos, fill = source, colour = source)) +
  geom_density(alpha = 0.1, linewidth = 0.5, adjust = 1.2) +
  geom_text(data = median_df,
            aes(x = 1, y = Inf,
                label = paste0(source, ": ", display_median, " nt"),
                colour = source, vjust = vjust_pos),
            hjust = 0, size = 3, inherit.aes = FALSE, show.legend = FALSE) +
  scale_x_continuous(name   = "Distance from 3' splice site (nt)",
                     limits = c(1, NA),
                     breaks = c(1, seq(10, 70, 10)),
                     labels = c(-70, -60, -50, -40, -30, -20, -10, -1)) +
  scale_fill_manual(values = pal_source) +
  scale_colour_manual(values = pal_source) +
  labs(y = "Density", fill = NULL, colour = NULL) +
  theme_classic(base_size = 10) +
  theme(
    axis.title  = element_text(color = 'black', family = 'Helvetica'),
    axis.text   = element_text(color = 'black', family = 'Helvetica'),
    legend.text = element_text(color = 'black', family = 'Helvetica'))

ggsave(file.path(plot_dir, "bp_position_density.png"), p_bp_pos, width = 8, height = 5, dpi = 150)

# ── 2.7 Cross-comparisons between reference datasets ─────────────────────────

cross_compare <- function(ref_a, name_a, ref_b, name_b) {
  shared_ids <- intersect(ref_a$exon_id, ref_b$exon_id)
  col_a <- paste0("coord_", tolower(name_a))
  col_b <- paste0("coord_", tolower(name_b))

  cat(sprintf("\n=== %s vs %s | shared exons: %d ===\n", name_a, name_b, length(shared_ids)))

  closest <- ref_a %>%
    filter(exon_id %in% shared_ids) %>%
    select(exon_id, !!col_a := intron_up_coord) %>%
    inner_join(
      ref_b %>% filter(exon_id %in% shared_ids) %>%
        select(exon_id, !!col_b := intron_up_coord),
      by = "exon_id", relationship = "many-to-many"
    ) %>%
    mutate(dist = abs(.data[[col_a]] - .data[[col_b]])) %>%
    group_by(exon_id, .data[[col_a]]) %>%
    slice_min(dist, n = 1, with_ties = FALSE) %>%
    ungroup()

  for (tol in TOLERANCES)
    cat(sprintf("  ±%d nt: %d / %d (%.1f%%)\n",
                tol, sum(closest$dist <= tol), nrow(closest),
                100 * mean(closest$dist <= tol)))

  out <- sprintf("%s_vs_%s_bp_comparison.tsv", tolower(name_a), tolower(name_b))
  fwrite(closest, file.path(results_dir, out), sep = "\t")
  cat("Saved:", out, "\n")
}

cross_compare(mercer,  "Mercer",  taggart,    "Taggart")
cross_compare(mercer,  "Mercer",  labranchor, "LaBranchoR")
cross_compare(taggart, "Taggart", labranchor, "LaBranchoR")

# ══════════════════════════════════════════════════════════════════════════════
# 3. SUPPLEMENTARY TABLE — Top BP per exon with reference database matches
# ══════════════════════════════════════════════════════════════════════════════

# Top-1 BP per exon. For LaBranchoR predicted BPs, bp_end and intron_up_coord
# are equivalent (bp_end - 1 = intron_up_coord = canonical A position).
top1 <- bp_7mers %>%
  filter(order == 1L) %>%
  mutate(intron_up_coord_bp = bp_end - 1L)

exon_coord_tbl <- fread(
  here("libraries_design", "02_mutagenesis_libraries", "output", "genomic_coord_mut.tsv"),
  sep = '\t'
)
exon_coord_tbl <- exon_coord_tbl %>%
  filter(!grepl('del', identifier), start <= 70) %>%
  select(exon, start, CHROM, POS) %>%
  rename(chrom = CHROM, hg38_bpA_pos = POS) %>%
  distinct()

# Genomic coordinates of the canonical A
top1_coords <- top1 %>%
  inner_join(
    exon_coord_tbl,
    by = c("exon_id" = "exon", "intron_up_coord_bp" = "start")
  )

# LaBranchoR top-1 match (exact position)
lab_top1 <- labranchor %>%
  group_by(exon_id) %>%
  slice_max(prob, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  select(exon_id, lab_intron_up_coord = intron_up_coord, lab_prob = prob)

# Nearest Mercer BP per exon and distance
mercer_nearest <- top1 %>%
  select(exon_id, intron_up_coord_bp) %>%
  inner_join(mercer %>% select(exon_id, mercer_coord = intron_up_coord),
             by = "exon_id", relationship = "many-to-many") %>%
  mutate(dist = abs(intron_up_coord_bp - mercer_coord)) %>%
  group_by(exon_id) %>%
  slice_min(dist, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  select(exon_id, dist_mercer = dist)

# Nearest Taggart BP per exon and distance
taggart_nearest <- top1 %>%
  select(exon_id, intron_up_coord_bp) %>%
  inner_join(taggart %>% select(exon_id, taggart_coord = intron_up_coord),
             by = "exon_id", relationship = "many-to-many") %>%
  mutate(dist = abs(intron_up_coord_bp - taggart_coord)) %>%
  group_by(exon_id) %>%
  slice_min(dist, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  select(exon_id, dist_taggart = dist)

# WT PSI
wt_psi_tbl <- psi_df %>%
  filter(grepl("wt", variant_id)) %>%
  distinct(exon_id, wt_psi)

supp_table <- top1_coords %>%
  left_join(lab_top1,        by = "exon_id") %>%
  left_join(mercer_nearest,  by = "exon_id") %>%
  left_join(taggart_nearest, by = "exon_id") %>%
  left_join(wt_psi_tbl,      by = "exon_id") %>%
  left_join(groups %>% select(exon_id, bp_group = group), by = "exon_id") %>%
  mutate(
    match_labranchor  = !is.na(lab_intron_up_coord) &
      intron_up_coord_bp == lab_intron_up_coord,
    match_mercer_4nt  = !is.na(dist_mercer)  & dist_mercer  <= 4L,
    match_taggart_4nt = !is.na(dist_taggart) & dist_taggart <= 4L
  ) %>%
  select(
    exon_id, label, bp_group, wt_psi,
    chrom, hg38_bpA_pos,
    bp_start, bp_end, intron_up_coord_bp, bp_seq,
    lab_intron_up_coord, lab_prob, match_labranchor,
    dist_mercer,  match_mercer_4nt,
    dist_taggart, match_taggart_4nt
  ) %>%
  arrange(label, exon_id)

fwrite(supp_table, file.path(results_dir, "supplementary_table_top_BP.tsv"), sep = "\t")
cat("\nSupplementary table:", nrow(supp_table), "exons\n")

match_summary_by_label <- supp_table %>%
  group_by(label) %>%
  summarise(
    n                 = n(),
    pct_match_lab     = round(100 * mean(match_labranchor,  na.rm = TRUE), 1),
    pct_match_mercer  = round(100 * mean(match_mercer_4nt,  na.rm = TRUE), 1),
    pct_match_taggart = round(100 * mean(match_taggart_4nt, na.rm = TRUE), 1),
    median_dist_mercer  = median(dist_mercer,  na.rm = TRUE),
    median_dist_taggart = median(dist_taggart, na.rm = TRUE),
    .groups = "drop"
  )
cat("\n=== Match summary ===\n")
print(match_summary_by_label)
fwrite(match_summary_by_label, file.path(results_dir, "match_summary_by_label.tsv"), sep = "\t")

cat("\nDone.\n")
