# =============================================================================
# analysis/config.R — Central path definitions for all analysis scripts.
# Source at the top of each script: source(here::here("analysis", "config.R"))
# =============================================================================

library(here)

# ── Core outputs ──────────────────────────────────────────────────────────────
SUP_TABLES_DIR <- here("results", "supplementary_tables")
MASTER_TABLE   <- file.path(SUP_TABLES_DIR, "Supplementary_Table4.tsv")
COVERAGE_FILE  <- here("results", "psi_per_variant", "coverage_per_exon.tsv")

# ── Pipeline outputs (generated by psi_per_variant; gitignored) ────────────
PSI_FINAL_DIR  <- here("results", "psi_per_variant")

# ── Library design ─────────────────────────────────────────────────────────────
METADATA_FILE  <- here("libraries_design", "02_mutagenesis_libraries", "exon_list_with_metadata.tsv")
VASTDB_FILE    <- here("libraries_design", "01_wt_screening_libraries", "necessary_file",
                       "VastDB", "VastDB_hg38_merged.tsv")
# Per-exon table with VastDB average PSI + SS scores: generated by
# libraries_design/01_wt_screening_libraries/ pipeline step 03 (gitignored).
VASTDB_SS_FILE <- here("libraries_design", "01_wt_screening_libraries", "output",
                       "03_exon_data_basic_gencode_release_july2023_with_sequence_and_vastDB.tsv")

# ── Databases ──────────────────────────────────────────────────────────────────
# Per-exon splice-site scores + z-scores: generated by 03.3_mutational_sensitivity_splice_site.R
# (requires genome-wide MaxEntScan scores; commit the output so downstream scripts work without them)
EXON_SS_INFO_FILE  <- here("data", "databases", "exon_ss_info.tsv")
MAXENTSCAN_SS5     <- here("data", "databases", "maxentscan", "scores5.txt")
MAXENTSCAN_SS3     <- here("data", "databases", "maxentscan", "scores3.txt")
MAXENTSCAN_GENOME_SS5  <- here("data", "databases", "maxentscan", "donor_ss_score_genome.txt.gz")
MAXENTSCAN_GENOME_SS3  <- here("data", "databases", "maxentscan", "acceptor_ss_score_genome.txt.gz")
# NOTE: Download from https://splicevardb.org (download the full database TSV)
#       and place at the path below.  Not committed to the repository due to size.
SPLICEVARDB_FILE   <- here("data", "databases", "SpliceVarDB", "20250224_splicevardb.download.tsv")
OTHER_DMS_FILE     <- here("data", "databases", "other_dms", "other_dataset.txt")
# NOTE: Download from GEO (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE307247),
#       file GSE307247_Processed_PSIs_All_Cells.csv.gz — decompress and place at path below.
#       Not committed to the repository due to size.
KOPLIK_FILE        <- here("data", "databases", "other_dms", "GSE307247_Processed_PSIs_All_Cells.csv")
BRANCHPOINT_DIR    <- here("data", "databases", "branch_point")
FAS_INDEL_FILE     <- here("data", "databases", "fas_indel", "psi_fas_indel_Baeza-Centurion_2025.txt")
LIFTOVER_CHAIN     <- here("data", "databases", "liftover", "hg19ToHg38.over.chain")

# ── Outputs ────────────────────────────────────────────────────────────────────
FIGURES_DIR    <- here("figures")
